

---

# Numpy


Sinonimo de *Numerical Python*, `numpy` es una librería que proporciona herramientas para trabajar con alto rendimiento sobre arreglos multidimensionales. 


## Características
Dentro de las principales características de `numpy` se encuentran:
- Ofrece un poderoso objeto para manipular arreglos multidimensionales: `ndarray`.
- Posee herramientas para realizar operaciones matemáticas y lógicas sobre arreglos, operaciones relacionadas con algebra lineal, transformadas de Fourier, entre otras.

Para importar los módulos de la librería `numpy`, por convención se utiliza:

In [ ]:
import numpy as np   # 'np' alias de numpy



---
# Arrays


Las funcionalidades de `numpy` se basan en en el objeto `ndarray`.

Un `ndarray`, también conocido por el alias de `array`, es un arreglo N-dimensional con elementos del mismo tipo e indexado por una tupla de enteros positivos.


```python
a = numpy.array(data, dtype = None, ndmin = 0, ...)
```
- data: datos de mismo tipo en forma de matriz o una secuencia anidada.
- dtype (opcional): tipos de datos deseados en el arreglo. 
- ndmin: especifica el número mínimo de dimensiones del arreglo resultante.



## Creación de Arrays

La forma mas facil de crear un arreglo es utilizando el objeto `ndarray`.

In [ ]:
a = np.array([[0,1,2,3],[3,2,1,0],[1,1,1,1]])  
a

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 1, 1, 1]])



Dentro de los principales atributos del objeto `ndarray`, se encuentran:
- `ndarray.shape`: tupla con las dimensiones del arreglo. 
- `ndarray.ndim`: numero de dimensiones del arreglo.
- `ndarray.size`: número de elementos del arreglo.
- `ndarray.dtype`: tipo de dato de los elementos del arreglo. 

In [ ]:
a.shape

(3, 4)

In [ ]:
a.ndim

2

In [ ]:
a.size

12

In [ ]:
a.dtype

dtype('int64')



Numpy cuenta con funciones especiales para crear arreglos con valores definidos por defecto, por ejemplo:
- **zeros**: crea arreglo solamente con 0's.
- **ones**: crea arreglo solamente con 1's.
- **eye**: crea una matriz identidad de tamaño n.
- **empty**: crea un arreglo sin inicializar de forma y dtype especificados.
- **full**: crea un arreglo con un valor constante especificado.

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([5,1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((2,3), dtype=int)

array([[73810112,        0,        0],
       [       0,        0,        0]])



## Aritmética con Arrays

El objeto `ndarray` es importante porque permite realizar cualquier operación entre arreglos sin escribir ningún bucle *for*.

Cualquier operación aritmética con arreglos del mismo tamaño aplica una operación elemento a elemento:

In [ ]:
a*a

array([[0, 1, 4, 9],
       [9, 4, 1, 0],
       [1, 1, 1, 1]])

In [ ]:
a+a

array([[0, 2, 4, 6],
       [6, 4, 2, 0],
       [2, 2, 2, 2]])



Las operaciones aritméticas con escalares se aplica a cada elemento del arreglo.

In [ ]:
2*a

array([[0, 2, 4, 6],
       [6, 4, 2, 0],
       [2, 2, 2, 2]])

In [ ]:
1+a

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [2, 2, 2, 2]])



Finalmente, las comparaciones entre arreglos de la misma dimensión generan un arreglo booleano.

In [ ]:
b = np.ones([3,4])  
a>b

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])



##  Indexing y slicing en Arrays

Tecnicas muy similares de *indexing* y *slicing* para acceder a las *listas de Python* son también utilizadas en los *Arrays de Numpy*. Sin embargo, una de las principales diferencias es que los subconjuntos son vistas, es decir, cualquier cambio modifica directamente al array original.


In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3:6] =10
a

array([ 0,  1,  2, 10, 10, 10,  6,  7,  8,  9])

In [ ]:
b = a[3:6]
b[:] = 5
a

array([0, 1, 2, 5, 5, 5, 6, 7, 8, 9])



Si se quiere copiar una parte de un arreglo en lugar de una vista, es necesario copiar explícitamente el arreglo.

In [ ]:
b = a[3:6].copy()

In [ ]:
b[:2]=1
b

array([1, 1, 5])

In [ ]:
a

array([0, 1, 2, 5, 5, 5, 6, 7, 8, 9])



El principo es el mismo para arreglos multidimensionales.

In [ ]:
a = np.arange(64).reshape(4,4,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [ ]:
a[0,:,0]

array([ 0,  4,  8, 12])

In [ ]:
a[0,:2,2:]

array([[2, 3],
       [6, 7]])

In [ ]:
a[::2,1,:]

array([[ 4,  5,  6,  7],
       [36, 37, 38, 39]])



## Funciones universales

Las funciones universales son funciones que ejecutan operaciones element-wise sobre los datos en los arreglos.

Generalmente, este tipo de funciones se aplican a cada elemento de un arreglo, por ejemplo:

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = np.sqrt(a)
b

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.exp(b)

array([1.        , 2.71828183, 4.11325038, 5.65223367, 7.3890561 ])



Por otro lado, hay funciones universales que realizan operaciones con 2 arrays y regresan un array como salida.

In [ ]:
np.add(a,a)

array([0, 2, 4, 6, 8])

In [ ]:
np.multiply(a,a)

array([ 0,  1,  4,  9, 16])

In [ ]:
np.power(a,a)

array([  1,   1,   4,  27, 256])



## Filtros en Arrays

Suponga que desea tomar el valor de una matriz `X` cuando el valor correspondiente en una condición es True, y de lo contrario tome el valor de la matriz `Y`. Dentro de *Numpy* hay una función llamada **np.where** que resuelve la situación anterior.

```python
result = np.where(cond, xarr, yarr)
```

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
np.where(xarr>1.3,0,1)

array([1, 1, 1, 0, 0])



## Métodos matemáticos y estadísticos

Un conjunto de funciones matemáticas que computan estadísticas sobre una matriz completa o sobre los datos a lo largo de un eje son accesibles como métodos de la clase `ndarray`. Las funciones como suma, media y desviación estándar se pueden usar llamando al método de instancia de matriz o usando la función * numpy * de nivel superior.

In [ ]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a.mean()

4.0

In [ ]:
np.mean(a)

4.0



La operación anterior se ha realizado en toda la matriz, pero es posible especificar el eje, como se muestra a continuación:

In [ ]:
a.sum(axis=1)

array([ 3, 12, 21])

In [ ]:
np.sum(a,axis=0)

array([ 9, 12, 15])

In [ ]:
a.max(axis=1)

array([2, 5, 8])

In [ ]:
a.std(0)

array([2.44948974, 2.44948974, 2.44948974])